spring:
  application:
    name: account-manager
  datasource:
    url: jdbc:h2:file:./db/accountManagerDb;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:accountManagerDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true